<?php 

    /*+**********************************************************************************
     * The contents of this file are subject to the vtiger CRM Public License Version 1.0
     * ("License"); You may not use this file except in compliance with the License
     * The Original Code is: vtiger CRM Open Source
     * The Initial Developer of the Original Code is vtiger.
     * Portions created by vtiger are Copyright (C) vtiger.
     * Portions created by Ido Kobelkowsky are Copyright (C) yalla ya!.
     * All Rights Reserved.
     *  ********************************************************************************
     *  Author       : Ido Kobelkowsky
     ************************************************************************************/
    
$languageStrings = array (
  'LBL_ADD_RECORD' => 'הוסף מטבע',
  'LBL_EDIT_CURRENCY' => 'מטבע עריכה',
  'LBL_ADD_NEW_CURRENCY' => 'הוסף מטבע חדש',
  'LBL_CURRENCY_NAME' => 'שם המטבע',
  'LBL_CURRENCY_CODE' => 'קוד מטבע',
  'LBL_CURRENCY_SYMBOL' => 'סמל',
  'LBL_CONVERSION_RATE' => 'שער חליפין',
  'LBL_ENTER_CONVERSION_RATE' => 'הזן את שיעור ההמרות',
  'LBL_CURRENCY_STATUS_DESC' => 'הפעל תיבת סימון לביצוע מטבע פעיל',
  'LBL_TRANSFER_CURRENCY' => 'מטבע העברה',
  'LBL_CURRENT_CURRENCY' => 'מטבע נוכחי',
  'Albania, Leke' => 'אלבניה, לקה',
  'Argentina, Pesos' => 'ארגנטינה, פסוס',
  'Aruba, Guilders' => 'ארובה, גילדן',
  'Australia, Dollars' => 'אוסטרליה, דולר',
  'Azerbaijan, New Manats' => 'אזרביג\'אן, ניו מאנאטס',
  'Bahamas, Dollars' => 'איי בהאמה, דולר',
  'Bahrain, Dinar' => 'בחריין, דינר',
  'Barbados, Dollars' => 'ברבדוס, דולר',
  'Belarus, Rubles' => 'בלארוס, Rubles',
  'Belize, Dollars' => 'בליז, דולר',
  'Bermuda, Dollars' => 'ברמודה, דולר',
  'Bolivia, Bolivianos' => 'בוליביה, בוליביה',
  'Convertible Marka' => 'מארק להמרה',
  'Botswana, Pulas' => 'בוצואנה, פולס',
  'Bulgaria, Leva' => 'Bulgaria, Leva',
  'Brazil, Reais' => 'ברזיל, רייס',
  'Great Britain Pounds' => 'לירות שטרלינג',
  'Brunei Darussalam, Dollars' => 'ברוניי דרוסלאם, דולר',
  'Canada, Dollars' => 'קנדה, דולר',
  'Cayman Islands, Dollars' => 'איי קיימן, דולר',
  'Chile, Pesos' => 'צ\'ילה, פסוס',
  'Colombia, Pesos' => 'קולומביה, פסוס',
  'Costa Rica, Colón' => 'קוסטה ריקה, קולון',
  'Croatia, Kuna' => 'קרואטיה, קונה',
  'Cuba, Pesos' => 'קובה, פסוס',
  'Cyprus, Pounds' => 'קפריסין, פאונד',
  'Czech Republic, Koruny' => 'צ\'כיה, קורוני',
  'Denmark, Kroner' => 'דנמרק, קרון',
  'Dominican Republic, Pesos' => 'הרפובליקה הדומיניקנית, פסוס',
  'East Caribbean, Dollars' => 'מזרח קריבי, דולר',
  'Egypt, Pounds' => 'מצרים, פאונד',
  'El Salvador, Colón' => 'אל סלבדור, קולון',
  'England, Pounds' => 'אנגליה, פאונד',
  'Estonia, Krooni' => 'Estonia, Krooni',
  'Euro' => 'יורו',
  'Falkland Islands, Pounds' => 'איי פוקלנד, פאונד',
  'Fiji, Dollars' => 'פיג \'י, דולר',
  'Ghana, Cedis' => 'גאנה, Cedis',
  'Gibraltar, Pounds' => 'גיברלטר, פאונד',
  'Guatemala, Quetzales' => 'גואטמלה, קוצ\'אלס',
  'Guernsey, Pounds' => 'גרנזי, פאונד',
  'Guyana, Dollars' => 'גיאנה, דולר',
  'Honduras, Lempiras' => 'הונדורס, Lempiras',
  'LvHong Kong, Dollars ' => 'LvHong קונג, דולר',
  'Hungary, Forint' => 'Hungary, פורינט',
  'Iceland, Krona' => 'איסלנד, כרונה',
  'India, Rupees' => 'הודו, רופיות',
  'Indonesia, Rupiahs' => 'אינדונזיה, רופיות',
  'Iran, Rials' => 'איראן, ריאל',
  'Isle of Man, Pounds' => 'האי מאן, פאונד',
  'Israel, New Shekels' => 'ישראל, שקלים חדשים',
  'Jamaica, Dollars' => 'ג \'מייקה, דולר',
  'Japan, Yen' => 'יפן, ין',
  'Jersey, Pounds' => 'ג \'רזי, פאונד',
  'Kazakhstan, Tenge' => 'קזחסטן, טנג',
  'Korea (North), Won' => 'קוריאה (צפון), וון',
  'Korea (South), Won' => 'קוריאה (דרום), Won',
  'Kyrgyzstan, Soms' => 'קירגיזסטן, סומס',
  'Laos, Kips' => 'לאוס, קיפס',
  'Latvia, Lati' => 'Latvia, Lati',
  'Lebanon, Pounds' => 'לבנון, פאונד',
  'Liberia, Dollars' => 'ליבריה, דולר',
  'Switzerland Francs' => 'פרנק שוויץ',
  'Lithuania, Litai' => 'Lithuania, Litai',
  'Macedonia, Denars' => 'מקדוניה, דנארס',
  'Malaysia, Ringgits' => 'מלזיה, רינגיטס',
  'Malta, Liri' => 'מלטה, לירי',
  'Mauritius, Rupees' => 'מאוריציוס, רופי',
  'Mexico, Pesos' => 'מקסיקו, פסוס',
  'Mongolia, Tugriks' => 'מונגוליה, טוגריקס',
  'Mozambique, Meticais' => 'מוזמביק, מטיקאיס',
  'Namibia, Dollars' => 'נמיביה, דולר',
  'Nepal, Rupees' => 'נפאל, רופיות',
  'Netherlands Antilles, Guilders' => 'האנטילים ההולנדיים, הגילדה',
  'New Zealand, Dollars' => 'ניו זילנד, דולר',
  'Nicaragua, Cordobas' => 'ניקרגואה, קורדובה',
  'Nigeria, Nairas' => 'ניגריה, נאיראס',
  'North Korea, Won' => 'צפון קוריאה, Won',
  'Norway, Krone' => 'נורבגיה, Krone',
  'Oman, Rials' => 'עומאן, ריאלים',
  'Pakistan, Rupees' => 'פקיסטן, רופי',
  'Panama, Balboa' => 'פנמה, בלבואה',
  'Paraguay, Guarani' => 'פרגוואי, גואראני',
  'Peru, Nuevos Soles' => 'פרו, Nuevos Soles',
  'Philippines, Pesos' => 'פיליפינים, פסוס',
  'Poland, Zlotych' => 'Poland, Zlotych',
  'Qatar, Rials' => 'קטאר, ריאל',
  'Romania, New Lei' => 'רומניה, ניו ליי',
  'Russia, Rubles' => 'רוסיה, רובלים',
  'Saint Helena, Pounds' => 'סנט הלנה, פאונד',
  'Saudi Arabia, Riyals' => 'סעודיה, ריאל',
  'Serbia, Dinars' => 'סרביה, דינר',
  'Seychelles, Rupees' => 'סיישל, רופי',
  'Singapore, Dollars' => 'סינגפור, דולר',
  'Solomon Islands, Dollars' => 'איי שלמה, דולר',
  'Somalia, Shillings' => 'סומליה, שילינגים',
  'South Africa, Rand' => 'דרום אפריקה, רנד',
  'South Korea, Won' => 'דרום קוריאה, Won',
  'Sri Lanka, Rupees' => 'סרי לנקה, רופי',
  'Sweden, Kronor' => 'Sweden, Kronor',
  'Switzerland, Francs' => 'שוויץ, פרנק',
  'Suriname, Dollars' => 'סורינם, דולר',
  'Syria, Pounds' => 'סוריה, פאונד',
  'Taiwan, New Dollars' => 'טייוואן, דולר חדש',
  'Thailand, Baht' => 'תאילנד, בהט',
  'Trinidad and Tobago, Dollars' => 'טרינידד וטובגו, דולר',
  'Turkey, New Lira' => 'טורקיה, לירה חדשה',
  'Turkey, Liras' => 'טורקיה, Liras',
  'Tuvalu, Dollars' => 'טובאלו, דולר',
  'Ukraine, Hryvnia' => 'אוקראינה, Hryvnia',
  'United Kingdom, Pounds' => 'בריטניה, לירה שטרלינג',
  'USA, Dollars' => 'ארה"ב, דולר',
  'Uruguay, Pesos' => 'אורוגוואי, פסוס',
  'Uzbekistan, Sums' => 'אוזבקיסטן, סכומים',
  'Venezuela, Bolivares Fuertes' => 'ונצואלה, בוליבארס פוארטס',
  'Vietnam, Dong' => 'וייטנאם, דונג',
  'Zimbabwe Dollars' => 'דולר מזימבבואה',
  'China, Yuan Renminbi' => 'סין, יואן רנמינבי',
  'Afghanistan, Afghanis' => 'אפגניסטן, אפגנים',
  'Cambodia, Riels' => 'קמבודיה, ריאלים',
  'Jordan, Dinar' => 'ירדן, דינר',
  'Kenya, Shilling' => 'קניה, שילינג',
  'MADAGASCAR, Malagasy Ariary' => 'מדגסקר, מלגזי אריארי',
  'United Arab Emirates, Dirham' => 'איחוד האמירויות הערביות, דירהם',
  'United Republic of Tanzania, Shilling' => 'הרפובליקה של טנזניה, שילינג',
  'Yemen, Rials' => 'תימן, ריאל',
  'Zambia, Kwacha' => 'זמביה, קוואצ\'ה',
  'Malawi, kwacha' => 'מלאווי, קוואצ\'ה',
  'Tunisian, Dinar' => 'תוניסאי, דינר',
  'Moroccan, Dirham' => 'מרוקאי, דירהם',
);
$jsLanguageStrings = array (
  'JS_CURRENCY_DETAILS_SAVED' => 'פרטי מטבע נשמרו',
  'JS_CURRENCY_DELETED_SUEESSFULLY' => 'מטבע נמחק בהצלחה',
);
