<?php 

    /*+**********************************************************************************
     * The contents of this file are subject to the vtiger CRM Public License Version 1.0
     * ("License"); You may not use this file except in compliance with the License
     * The Original Code is: vtiger CRM Open Source
     * The Initial Developer of the Original Code is vtiger.
     * Portions created by vtiger are Copyright (C) vtiger.
     * Portions created by Ido Kobelkowsky are Copyright (C) yalla ya!.
     * All Rights Reserved.
     *  ********************************************************************************
     *  Author       : Ido Kobelkowsky
     ************************************************************************************/
    
$languageStrings = array (
  'LBL_PUBLISHER' => 'מוציא לאור',
  'LBL_LICENSE' => 'רישיון',
  'LBL_PUBLISHED_ON' => 'פורסם ב',
  'LBL_INSTALL' => 'להתקין',
  'LBL_UPGRADE' => 'שדרג',
  'LBL_VERSION' => 'גרסה',
  'LBL_DECLINE' => 'ירידה',
  'LBL_ACCEPT_AND_INSTALL' => 'קבל והתקן',
  'LBL_OK' => 'בסדר',
  'LBL_EXTENSION_NOT_COMPATABLE' => 'ההרחבה אינה תואמת',
  'LBL_INVALID_FILE' => 'קובץ לא תקין',
  'LBL_NO_LICENSE_PROVIDED' => 'לא ניתן רישיון',
  'LBL_INSTALLATION' => 'התקנה',
  'LBL_FAILED' => 'נכשל',
  'LBL_SUCCESSFULL' => 'בהצלחה',
  'LBL_INSTALLATION_LOG' => 'יומן התקנה',
  'LBL_UPDATED_MODULE' => ' המודול עודכן בהצלחה.',
  'LBL_UPDATING_MODULE' => 'מודול עדכון',
  'LBL_MARKET_PLACE' => 'מקום שוק',
  'LBL_VTIGER_EXTENSION_STORE' => 'Vtiger הרחבה חנות',
  'LBL_SEARCH_FOR_AN_EXTENSION' => 'חפש תוסף ..',
  'LBL_DOWNLOADS' => 'הורדות',
  'LBL_NO_EXTENSIONS_FOUND' => 'לא נמצאו תוספים',
  'LBL_REGISTER_TO_MARKET_PLACE' => 'הרשמה לשוק',
  'LBL_MARKETPLACE_REGISTRATION' => 'רישום שוק',
  'LBL_MARKETPLACE_LOGIN' => 'כניסה לשוק',
  'LBL_NEW_TO_MARKETPLCAE' => 'חדש ל\'חנות Android \'?',
  'LBL_CREATE_AN_ACCOUNT' => 'צור חשבון חדש',
  'LBL_SETUP_CARD_DETAILS' => 'הגדרת פרטי כרטיס',
  'LBL_SETUP_CARD' => 'כרטיס התקנה',
  'LBL_CARD_NUMBER' => 'מספר כרטיס',
  'LBL_EXP_MONTH' => 'חודש Exp',
  'LBL_EXP_YEAR' => 'שנת יציאה',
  'LBL_CVC_CODE' => 'קוד אימות כרטיס האשראי',
  'LBL_RESET' => 'אפס',
  'LBL_EXTENSION_STORE' => 'חנות הרחבה',
  'LBL_INSTALLED' => 'מותקן',
  'LBL_UPDATE_CARD_DETAILS' => 'עדכן פרטי כרטיס',
  'LBL_BY' => 'על ידי',
  'LBL_RATINGS' => 'דירוגים',
  'LBL_DESCRIPTION' => 'תיאור',
  'LBL_AUTHOR_INFORMATION' => 'מידע על הסופר',
  'LBL_AUTHOR_NAME' => 'שם המחבר',
  'LBL_PHONE' => 'מכשיר טלפון',
  'LBL_EMAIL' => 'דוא"ל',
  'LBL_SCREEN_SHOTS' => 'צילומי מסך',
  'LBL_CUSTOMER_RATINGS' => 'דירוג לקוחות',
  'LBL_CUSTOMER_REVIEWS' => 'חוות דעת של לקוחות',
  'LBL_WRITE_A_REVIEW' => 'כתוב ביקורת',
  'LBL_CUSTOMER_REVIEW' => 'ביקורת לקוחות',
  'LBL_REVIEW' => 'סקירה',
  'LBL_CUSTOMERS_REVIEWED' => 'לקוחות שנבדקו',
  'LBL_SINGLE_CUSTOMER_REVIEWED' => 'לקוח בודד נבדק',
  'LBL_INSTALLATION_FAILED' => 'ההתקנה נכשלה',
  'LBL_SUCCESSFULL_INSTALLATION' => 'התקנה מוצלחת',
  'LBL_INSTALL_FROM_ZIP' => 'התקן מ- Zip',
  'LBL_MORE_DETAILS' => 'פרטים נוספים',
  'Install' => 'להתקין',
  'Upgrade' => 'שדרג',
  'LBL_RATE_IT' => 'לדרג אותו.',
  'LBL_UNINSTALL' => 'הסר את ההתקנה',
  'LBL_LAUNCH' => 'הפעלה',
  'LBL_SIGN_UP_FOR_FREE' => 'הרשם בחינם',
  'LBL_EMAIL_ADDRESS' => 'כתובת דוא"ל',
  'LBL_FIRST_NAME' => 'שם פרטי',
  'LBL_LAST_NAME' => 'שם משפחה',
  'LBL_COMPANY_NAME' => 'שם החברה',
  'LBL_PASSWORD' => 'סיסמה',
  'LBL_CONFIRM_PASSWORD' => 'אשר סיסמה',
  'LBL_REGISTER' => 'הירשם',
  'LBL_EXTENSION_STORE_LOGIN' => 'כניסה',
  'LBL_REMEMBER_ME' => 'זכור אותי',
  'LBL_TRY_IT' => 'נסה זאת',
  'LBL_TRIAL_INSTALLED' => 'משפט מותקן',
  'LBL_BUY' => 'קנה',
  'LBL_LOGIN_TO_MARKET_PLACE' => 'כניסה לשוק',
  'LBL_LOGIN' => 'התחברות',
  'LBL_PHP_EXTENSION_LOADER_IS_NOT_AVAIABLE' => 'יש להתקין מטעין הרחבה',
  'LBL_INSTALL_EXTENSION_LOADER' => 'התקן את Load Loader',
  'LBL_TO_CONTINUE_USING_EXTENSION_STORE' => 'כדי להמשיך להשתמש בחנות הרחבה, אנא התקן',
  'LBL_DOWNLOAD' => 'הורד',
  'LBL_COMPATIABLE_EXTENSION' => ' ולאפשר לו להיות zend_extension.',
  'LBL_MORE_DETAILS_ON_INSTALLATION' => 'לקבלת פרטים נוספים על ההתקנה',
  'LBL_READ_HERE' => 'קרא כאן',
  'LBL_REVIEWS' => 'ביקורות',
  'LBL_SIGNUP_FOR_MARKET_PLACE' => 'הרשמה לשוק',
  'LBL_UNAUTHORIZED' => 'לא מורשה',
  'LBL_EXPIRY_DATE' => 'תאריך תפוגה',
  'LBL_LOGOUT' => 'להתנתק',
  'firstname' => 'שם פרטי',
  'lastname' => 'שם משפחה',
  'email' => 'דוא"ל',
  'company' => 'החברה',
  'Phone' => 'מכשיר טלפון',
  'Website' => 'אתר אינטרנט',
  'LBL_SECURITY_CODE' => 'קוד אבטחה',
  'LBL_WHAT_IS_SECURITY_CODE' => 'מהו קוד אבטחה?',
  'LBL_CARD_NUMBER_PLACEHOLDER' => 'מספר 16 ספרות על הכרטיס שלך',
  'LBL_SECURITY_CODE_HELP_CONTENT' => 'מספר CVV (כרטיס אימות כרטיס) בכרטיס האשראי / החיוב שלך הוא מספר 3 ספרות ב- VISA®, MasterCard® וכו \'. כרטיסי אשראי / כרטיסי חיוב.',
  'LBL_ENTER_REGISTERED_EMAIL' => 'הזן את כתובת הדוא"ל הרשומה שלך',
  'LBL_RESET_PASSWORD_LINK_EMAILED' => 'איפוס קישור הסיסמה נשלח אליך!',
  'LBL_FORGOT_PASSWORD' => 'שכחת את הסיסמא',
  'LBL_ALREADY_INSTALLED_MODULE_BUILDER' => 'כבר נוצר על ידי בונה מודול',
  'LBL_REVIEW_RESTRICTED' => 'סקירה מוגבלת',
);
$jsLanguageStrings = array (
  'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_THIS_EXTENSION' => 'אנא הגדר פרטי כרטיס כדי להתקין תוסף זה',
  'JS_UPDATE_CARD_DETAILS' => 'עדכן פרטי כרטיס',
  'JS_ON' => 'on',
  'JS_RATINGS' => 'דירוגים',
  'JS_INSTALLED' => 'מותקן',
  'JS_TRIAL_INSTALLED' => 'משפט מותקן',
  'JS_PLEASE_INSTALL_EXTENSION_LOADER_TO_INSTALL_THIS_EXTENSION_FROM_BELOW_LINK' => 'בבקשה להתקין מטעין הרחבה כדי להתקין את התוסף מלמטה הקישור',
  'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_INSTALLING_EXTENSION' => 'התחבר אל Marketplace כדי להתקין את התוסף',
  'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_EXTENSION' => 'נא להגדיר פרטים כרטיס ההתקנה כדי להתקין',
  'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_UNINSTALLING_EXTENSION' => 'התחבר אל Marketplace כדי להסיר את ההתקנה',
  'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_INSTALL_THIS_EXTENSION' => 'האם אתה בטוח שברצונך להתקין תוסף זה?',
  'JS_CARD_DETAILS_UPDATED' => 'פרטי הכרטיס עודכנו!',
  'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT_FROM_EXTENSION' => 'האם אתה בטוח שברצונך לצאת מהתוסף?',
  'JS_PASSWORDS_MISMATCH' => 'סיסמאות לא תואמות!',
  'JS_ARE_YOU_SURE_UNINSTALL' => 'האם אתה בטוח שברצונך להסיר את ההתקנה הזו',
  'JS_ARE_YOU_SURE_INSTALL' => 'האם אתה בטוח שברצונך להתקין תוסף זה',
);
