<?php 

    /*+**********************************************************************************
     * The contents of this file are subject to the vtiger CRM Public License Version 1.0
     * ("License"); You may not use this file except in compliance with the License
     * The Original Code is: vtiger CRM Open Source
     * The Initial Developer of the Original Code is vtiger.
     * Portions created by vtiger are Copyright (C) vtiger.
     * Portions created by Ido Kobelkowsky are Copyright (C) yalla ya!.
     * All Rights Reserved.
     *  ********************************************************************************
     *  Author       : Ido Kobelkowsky
     ************************************************************************************/
    
$languageStrings = array (
  'MailConverter' => 'ממיר דואר',
  'MailConverter_Description' => 'המרת הודעות דוא"ל לרשומות המתאימות',
  'MAILBOX' => 'תיבת דואר',
  'RULE' => 'כלל',
  'LBL_ADD_RECORD' => 'הוסף תיבת דואר',
  'ALL' => 'את כל',
  'UNSEEN' => 'לא נקרא',
  'LBL_MARK_READ' => 'סמן קריאה',
  'SEEN' => 'לקרוא',
  'LBL_EDIT_MAILBOX' => 'ערוך תיבת דואר',
  'LBL_CREATE_MAILBOX' => 'צור תיבת דואר',
  'LBL_BACK_TO_MAILBOXES' => 'חזרה לתיבות דואר',
  'LBL_MARK_MESSAGE_AS' => 'סמן את ההודעה כ-',
  'LBL_CREATE_MAILBOX_NOW' => 'צור תיבת דואר כעת',
  'LBL_ADDING_NEW_MAILBOX' => 'הוספת תיבת דואר חדשה',
  'MAILBOX_DETAILS' => 'פרטי תיבת דואר',
  'SELECT_FOLDERS' => 'בחר תיקיות',
  'ADD_RULES' => 'הוסף כללים',
  'CREATE_Leads_SUBJECT' => 'צור לייד',
  'CREATE_Contacts_SUBJECT' => 'צור איש קשר',
  'CREATE_Accounts_SUBJECT' => 'צור ארגון',
  'LBL_ACTIONS' => 'פעולות',
  'LBL_MAILBOX' => 'תיבת דואר',
  'LBL_RULE' => 'כלל',
  'LBL_CONDITIONS' => 'תנאים',
  'LBL_FOLDERS_SCANNED' => 'תיקיות סרוקות',
  'LBL_NEXT' => 'הבא',
  'LBL_FINISH' => 'סיים',
  'TO_CHANGE_THE_FOLDER_SELECTION_DESELECT_ANY_OF_THE_SELECTED_FOLDERS' => 'כדי לשנות את בחירת התיקייה בטל את הבחירה של כל התיקיות שנבחרו',
  'LBL_MAILCONVERTER_DESCRIPTION' => 'ממיר דואר מאפשר לך להגדיר את תיבת הדואר שלך כדי לסרוק את הודעות הדוא"ל שלך וליצור ישויות מתאימות ב- CRM Vtiger. <br /> אתה צריך גם להגדיר כללים כדי לציין מה פעולות צריך להתבצע על הודעות הדוא"ל שלך. <br /> הדואר האלקטרוני שלך הם סרק באופן אוטומטי, אלא אם השבתת את המשימה של סורק דואר ב מתזמן. <br /> <br /> <br />',
  'LBL_MAX_LIMIT_ONLY_TWO' => 'באפשרותך להגדיר רק שתי תיבות דואר',
  'LBL_IS_IN_RUNNING_STATE' => 'הוא פועל במצב',
  'LBL_SAVED_SUCCESSFULLY' => 'נשמר בהצלחה',
  'LBL_CONNECTION_TO_MAILBOX_FAILED' => 'ההתחברות לתיבת הדואר נכשלה.',
  'LBL_DELETED_SUCCESSFULLY' => 'נמחק בהצלחה',
  'LBL_RULE_DELETION_FAILED' => 'מחיקת הכלל נכשלה',
  'LBL_RULES_SEQUENCE_INFO_IS_EMPTY' => 'כללים מידע sequnce ריק',
  'LBL_SEQUENCE_UPDATED_SUCCESSFULLY' => 'רצף עודכן בהצלחה',
  'LBL_SCANNED_SUCCESSFULLY' => 'סרוק בהצלחה',
  'scannername' => 'שם הסורק',
  'server' => 'שם שרת IMAP',
  'protocol' => 'פרוטוקול',
  'username' => 'שם משתמש',
  'password' => 'סיסמה',
  'ssltype' => 'סוג SSL',
  'sslmethod' => 'שיטת SSL',
  'connecturl' => 'צור כתובת אתר',
  'searchfor' => 'לחפש',
  'markas' => 'לאחר הסריקה',
  'isvalid' => 'סטטוס',
  'time_zone' => 'אזור שרת הדואר',
  'scanfrom' => 'סרוק דואר מ',
  'YESTERDAY' => 'אתמול',
  'LBL_ENABLE' => 'הפעל',
  'LBL_DISABLE' => 'השבת',
  'LBL_STATUS_MESSAGE' => 'סמן כדי להפוך לפעיל',
  'LBL_VALIDATE_SSL_CERTIFICATE' => 'אימות תעודת SSL',
  'LBL_DO_NOT_VALIDATE_SSL_CERTIFICATE' => 'אל תתקין אישור SSL',
  'LBL_ALL_MESSAGES_FROM_LAST_SCAN' => 'כל ההודעות מסריקה אחרונה',
  'LBL_UNREAD_MESSAGES_FROM_LAST_SCAN' => 'הודעות שלא נקראו מסריקה אחרונה',
  'LBL_MARK_MESSAGES_AS_READ' => 'סמן הודעות כהודעות שנקראו',
  'LBL_I_DONT_KNOW' => 'אני לא יודע',
  'LBL_SCAN_NOW' => 'לסרוק עכשיו',
  'LBL_RULES_LIST' => 'רשימת כללים',
  'LBL_SELECT_FOLDERS' => 'בחר תיקיות',
  'LBL_SCANED_SUCCESSFULLY' => 'סרוק בהצלחה',
  'LBL_FOLDERS_INFO_IS_EMPTY' => 'פרטי התיקיות ריקים',
  'LBL_UPDATE_FOLDERS' => 'עדכון תיקיות',
  'fromaddress' => 'מ',
  'toaddress' => 'ל',
  'subject' => 'נושא',
  'body' => 'גוף',
  'matchusing' => 'התאמה',
  'action' => 'פעולה',
  'LBL_PRIORITY' => 'עדיפות',
  'PRIORITISE_MESSAGE' => 'גרור ושחרר את הבלוק כדי לתת עדיפות לכלל',
  'LBL_NOTE' => 'הערה',
  'LBL_MAILCONVERTER_DISABLE_MESSAGE' => 'ממיר דואר יוסר ב -31 ביולי. Mailroom מספק דרך קלה יותר לסרוק את הודעות הדוא"ל שלך. כדי להפעיל את Mailroom, אנא',
  'LBL_CLICK_HERE' => 'לחץ כאן',
  'LBL_ALL_CONDITIONS' => 'כל התנאים',
  'LBL_ANY_CONDITIOn' => 'כל תנאי',
  'Contains' => 'מכיל',
  'Not Contains' => 'לא מכיל',
  'Equals' => 'שווים',
  'Not Equals' => 'לא שווה',
  'Begins With' => 'התחל',
  'Ends With' => 'סוף',
  'Regex' => 'Regex',
  'LBL_FROM_ADDRESS_PLACE_HOLDER' => 'כתובת דוא"ל או שם תחום',
  'CREATE_HelpDesk_FROM' => 'יצירת כרטיס (עם איש קשר)',
  'CREATE_HelpDeskNoContact_FROM' => 'יצירת כרטיס (ללא קשר)',
  'UPDATE_HelpDesk_SUBJECT' => 'עדכון כרטיס',
  'LINK_Contacts_FROM' => 'הוסף איש קשר [FROM]',
  'LINK_Contacts_TO' => 'הוסף אל [TO]',
  'LINK_Accounts_FROM' => 'הוסף לארגון [FROM]',
  'LINK_Accounts_TO' => 'הוסף לארגון [TO]',
  'LINK_Leads_FROM' => 'הוסף לייד [FROM]',
  'LINK_Leads_TO' => 'הוסף להובלה [TO]',
  'CREATE_Potentials_SUBJECT' => 'יצירת הזדמנות (עם יצירת קשר)',
  'CREATE_PotentialsNoContact_SUBJECT' => 'יצירת הזדמנות (ללא קשר)',
  'LINK_Potentials_FROM' => 'הוסף הזדמנות [FROM]',
  'LINK_Potentials_TO' => 'הוסף הזדמנות [TO]',
  'LINK_HelpDesk_FROM' => 'הוסף כרטיס [FROM]',
  'LINK_HelpDesk_TO' => 'הוסף כרטיס [TO]',
  'LBL_UNSELECT_ALL' => 'בטל את הבחירה בכל',
  'LBL_CONVERT_EMAILS_TO_RESPECTIVE_RECORDS' => 'המרת הודעות דוא"ל לרשומות המתאימות',
  'LBL_DRAG_AND_DROP_BLOCK_TO_PRIORITISE_THE_RULE' => 'מספר הכלל מציין את העדיפות. גרור ושחרר כדי לשנות את העדיפות.',
  'LBL_ADD_RULE' => 'הוסף כלל',
  'LBL_EDIT_RULE' => 'ערוך כלל',
  'LBL_DELETE_RULE' => 'מחק כלל',
  'LBL_BODY' => 'גוף',
  'LBL_MATCH' => 'התאמה',
  'LBL_ACTION' => 'פעולה',
  'LBL_FROM' => 'מ',
  'LBL_CONNECTION_ERROR' => 'החיבור לתיבת הדואר נכשל. בדוק את חיבור הרשת ונסה שוב.',
  'LBL_RULE_CONDITIONS' => 'תנאי שלטון',
  'LBL_RULE_ACTIONS' => 'פעולות כלל',
  'LBL_AUTOFILL_VALUES_FROM_EMAIL_BODY' => 'ערכי מילוי אוטומטי מגוף אימייל',
  'LBL_DELIMITER' => 'דלימיטר',
  'LBL_COLON' => ': (המעי הגס)',
  'LBL_SEMICOLON' => '; (סמי קולון)',
  'LBL_DASH' => '- (מקף)',
  'LBL_EQUAL' => '= (שווה)',
  'LBL_GREATER_THAN' => '> (גדול מ)',
  'LBL_COLON_DASH' => ': - (קולון, מקף)',
  'LBL_COLON_EQUAL' => ': = (שווה-קולון)',
  'LBL_SEMICOLON_DASH' => '; - (מקף-פסיק)',
  'LBL_SEMICOLON_EQUAL' => '; = (נקודה-פסיק)',
  'LBL_EQUAL_GREATER_THAN' => '=> (שווה לגודל)',
  'LBL_OTHER' => 'אחר',
  'LBL_DELIMITER_INFO' => 'בחר את התו המפריד בין ערכים מהתוויות בגוף הדוא"ל שלך',
  'LBL_EMAIL_BODY_INFO' => 'העתק טקסט מדוא"ל לדוגמה כדי לסרוק לתוך התיבה הבאה. Vtiger CRM ינסה לאתר ערכים ולעזור לך למפות לשדות CRM.',
  'LBL_SAMPLE_BODY_TEXT' => 'טקסט גוף לדוגמה',
  'LBL_FIND_FIELDS' => 'לחץ כאן כדי למצוא ערכים מגוף הדוא"ל',
  'LBL_BODY_FIELDS' => 'ערכים מהאימייל',
  'LBL_CRM_FIELDS' => 'שדות CRM',
  'LBL_MAP_TO_CRM_FIELDS' => 'ערכי ערכי שדות CRM',
  'SELECT_FIELD' => 'בחר שדה',
  'LBL_SAVE_MAPPING_INFO' => 'שמירת כלל גוף עבור כלל קיים של ממיר דואר תחליף את כלל הגוף הקיים עבור כלל זה.',
  'LBL_MULTIPLE_FIELDS_MAPPED' => 'לא ניתן למפות שדה CRM אחד עם שדות מרובים',
  'LBL_BODY_RULE' => 'גוף הגוף מוגדר',
  'LBL_MAIL_SCANNER_INACTIVE' => 'תיבת דואר זו נמצאת במצב לא פעיל',
  'LBL_NO_RULES' => 'לא הוגדרו כללים עבור תיבת דואר זו',
  'LBL_SCANNERNAME_ALPHANUMERIC_ERROR' => 'שם הסורק מקבל רק ערך אלפא-נומרי. תווים מיוחדים אינם מורשים.',
  'LBL_SERVER_NAME_ERROR' => 'שם שרת לא חוקי. תווים מיוחדים אינם מותרים עבור שם השרת.',
  'LBL_USERNAME_ERROR' => 'הזן כתובת דוא"ל חוקית עבור שם המשתמש.',
  'servertype' => 'סוג שרת',
  'LBL_DUPLICATE_USERNAME_ERROR' => 'יש כבר ממיר דואר מוגדר עם כתובת דוא"ל זו. לא ניתן ליצור שכפל ממיר דואר עם אותה כתובת דוא"ל.',
  'LBL_DUPLICATE_SCANNERNAME_ERROR' => 'יש כבר ממיר דואר מוגדר עם שם זה. לא ניתן ליצור ממיר דואר עם שם כפול.',
);
$jsLanguageStrings = array (
  'JS_MAILBOX_DELETED_SUCCESSFULLY' => 'MailBox נמחק בהצלחה',
  'JS_MAILBOX_LOADED_SUCCESSFULLY' => 'MailBox טעון בהצלחה',
  'JS_SELECT_ATLEAST_ONE' => 'נא מפה atleast שדה אחד',
  'JS_SERVER_NAME' => 'הזן שם שרת',
  'JS_TIMEZONE' => 'אזור שרת הדואר',
  'JS_SCAN_FROM' => 'סרוק דואר מ',
  'JS_TIMEZONE_INFO' => 'בחר אזור זמן שבו נמצא שרת הדואר שלך. בחירת אזור זמן שגוי עלולה לדלג על הודעות דואר מסוימות מסריקה.',
  'JS_SCAN_FROM_INFO' => 'שדה זה מחליט אם יש לסרוק את כל הדואר בתיבת הדואר שלך או לשלוח הודעות דואר שנחתו בתיבת הדואר שלך אתמול או מאוחר יותר. שדה זה חל רק על תצורה בפעם הראשונה או כאשר אתה בוחר תיקייה חדשה לסריקה.',
  'JS_SELECT_ONE_FOLDER' => 'עליך לבחור atleast תיקייה אחת.',
);
