<?php 

    /*+**********************************************************************************
     * The contents of this file are subject to the vtiger CRM Public License Version 1.0
     * ("License"); You may not use this file except in compliance with the License
     * The Original Code is: vtiger CRM Open Source
     * The Initial Developer of the Original Code is vtiger.
     * Portions created by vtiger are Copyright (C) vtiger.
     * Portions created by Ido Kobelkowsky are Copyright (C) yalla ya!.
     * All Rights Reserved.
     *  ********************************************************************************
     *  Author       : Ido Kobelkowsky
     ************************************************************************************/
    
$languageStrings = array (
  'LBL_NEW' => 'חדש',
  'LBL_WORKFLOW' => 'זרימת עבודה',
  'LBL_CREATING_WORKFLOW' => 'יצירת WorkFlow',
  'LBL_EDITING_WORKFLOW' => 'עריכת זרימת עבודה',
  'LBL_ADD_RECORD' => 'זרימת עבודה חדשה',
  'LBL_STEP_1' => 'שלב 1',
  'LBL_ENTER_BASIC_DETAILS_OF_THE_WORKFLOW' => 'הזן פרטים בסיסיים של זרימת העבודה',
  'LBL_SPECIFY_WHEN_TO_EXECUTE' => 'ציין מתי לבצע את זרימת העבודה הזו',
  'ON_FIRST_SAVE' => 'רק על הציל הראשון',
  'ONCE' => 'עד הפעם הראשונה שהמצב נכון',
  'ON_EVERY_SAVE' => 'בכל פעם שהרשומה נשמרת',
  'ON_MODIFY' => 'בכל פעם שהרשומה משתנה',
  'ON_SCHEDULE' => 'לוח זמנים',
  'MANUAL' => 'מערכת',
  'SCHEDULE_WORKFLOW' => 'תזמון עבודה',
  'ADD_CONDITIONS' => 'הוסף תנאים',
  'ADD_TASKS' => 'הוסף פעולות',
  'LBL_EXPRESSION' => 'ביטוי',
  'LBL_FIELD_NAME' => 'שדה',
  'LBL_SET_VALUE' => 'הגדר ערך',
  'LBL_USE_FIELD' => 'השתמש בשדה',
  'LBL_USE_FUNCTION' => 'השתמש בפונקציה',
  'LBL_RAW_TEXT' => 'טקסט גולמי',
  'LBL_ENABLE_TO_CREATE_FILTERS' => 'אפשר ליצור מסננים',
  'LBL_CREATED_IN_OLD_LOOK_CANNOT_BE_EDITED' => 'זרימת עבודה זו נוצרה במראה ישן יותר. לא ניתן לערוך את התנאים שנוצרו במראה ישן יותר. אתה יכול לבחור ליצור מחדש את התנאים, או להשתמש בתנאים הקיימים מבלי לשנות אותם.',
  'LBL_USE_EXISTING_CONDITIONS' => 'השתמש בתנאים הקיימים',
  'LBL_RECREATE_CONDITIONS' => 'תנאי יצירה מחדש',
  'LBL_SAVE_AND_CONTINUE' => 'שמור המשך',
  'LBL_ACTIVE' => 'פעיל',
  'LBL_TASK_TYPE' => 'סוג פעולה',
  'LBL_TASK_TITLE' => 'כותרת פעולה',
  'LBL_ADD_TASKS_FOR_WORKFLOW' => 'הוסף פעולה עבור זרימת עבודה',
  'LBL_EXECUTE_TASK' => 'בצע פעולה',
  'LBL_SELECT_OPTIONS' => 'בחר אופציות',
  'LBL_ADD_FIELD' => 'הוסף שדה',
  'LBL_ADD_TIME' => 'הוסף זמן',
  'LBL_TITLE' => 'כותרת',
  'LBL_PRIORITY' => 'עדיפות',
  'LBL_ASSIGNED_TO' => 'שהוקצה ל',
  'LBL_TIME' => 'זמן',
  'LBL_DUE_DATE' => 'תאריך להגשה',
  'LBL_THE_SAME_VALUE_IS_USED_FOR_START_DATE' => 'אותו ערך משמש לתאריך ההתחלה',
  'LBL_EVENT_NAME' => 'שם אירוע',
  'LBL_TYPE' => 'הקלד',
  'LBL_METHOD_NAME' => 'שם שיטה',
  'LBL_RECEPIENTS' => 'מקבלות',
  'LBL_ADD_FIELDS' => 'הוסף שדות',
  'LBL_SMS_TEXT' => 'טקסט SMS',
  'LBL_SET_FIELD_VALUES' => 'הגדר ערכי שדה',
  'LBL_IN_ACTIVE' => 'פעיל',
  'LBL_SEND_NOTIFICATION' => 'שלח הודעה',
  'LBL_START_TIME' => 'שעת התחלה',
  'LBL_START_DATE' => 'תאריך התחלה',
  'LBL_END_TIME' => 'זמן סיום',
  'LBL_END_DATE' => 'תאריך סיום',
  'LBL_ENABLE_REPEAT' => 'הפעל חזרה',
  'LBL_NO_METHOD_IS_AVAILABLE_FOR_THIS_MODULE' => 'אין שיטה זמינה עבור מודול זה',
  'LBL_NO_TASKS_ADDED' => 'אין פעולות',
  'LBL_CANNOT_DELETE_DEFAULT_WORKFLOW' => 'לא ניתן למחוק את זרימת העבודה המוגדרת כברירת מחדל',
  'LBL_MODULES_TO_CREATE_RECORD' => 'צור רשומה ב',
  'LBL_EXAMPLE_EXPRESSION' => 'ביטוי',
  'LBL_EXAMPLE_RAWTEXT' => 'Rawtext',
  'LBL_VTIGER' => 'Vtiger',
  'LBL_EXAMPLE_FIELD_NAME' => 'שדה',
  'LBL_NOTIFY_OWNER' => 'לא',
  'LBL_ANNUAL_REVENUE' => 'הכנסה שנתית',
  'LBL_EXPRESSION_EXAMPLE2' => 'אם mailingcountry == \'India\' ולאחר מכן concat (firstname, \'\', lastname) concat אחר (Lastname, \'\', firstname) end',
  'LBL_FROM' => 'מ',
  'LBL_RUN_WORKFLOW' => 'הפעלה של זרימת עבודה',
  'LBL_AT_TIME' => 'בזמן',
  'LBL_HOURLY' => 'מדי שעה',
  'Optional' => 'אופציונאלי',
  'ENTER_FROM_EMAIL_ADDRESS' => 'הזן כתובת דוא"ל מאת',
  'LBL_ADD_TASK' => 'הוסף פעולה',
  'Portal Pdf Url' => 'כתובת אתר של פורטל PDF',
  'LBL_DAILY' => 'יומי',
  'LBL_WEEKLY' => 'שבועי',
  'LBL_ON_THESE_DAYS' => 'בימים האלו',
  'LBL_MONTHLY_BY_DATE' => 'חודשי לפי תאריך',
  'LBL_MONTHLY_BY_WEEKDAY' => 'חודשי עד שבוע',
  'LBL_YEARLY' => 'שנתי',
  'LBL_SPECIFIC_DATE' => 'בתאריך ספציפי',
  'LBL_CHOOSE_DATE' => 'בחר תאריך',
  'LBL_SELECT_MONTH_AND_DAY' => 'בחר חודש ותאריך',
  'LBL_SELECTED_DATES' => 'תאריכים נבחרים',
  'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'חרגת מהמגבלה המקסימלית',
  'LBL_NEXT_TRIGGER_TIME' => 'לחץ על זמן ההדק הבא',
  'LBL_ADD_TEMPLATE' => 'הוסף תבנית',
  'LBL_LINEITEM_BLOCK_GROUP' => 'LineItems לחסום מס קבוצה',
  'LBL_LINEITEM_BLOCK_INDIVIDUAL' => 'LineItems לחסום מס יחיד',
  'LBL_MESSAGE' => 'הודעה',
  'LBL_ADD_PDF' => 'הוסף PDF',
  'Calendar' => 'משימה',
  'Send Mail' => 'שלח מייל',
  'Invoke Custom Function' => 'הפעל פונקציה מותאמת אישית',
  'Create Todo' => 'צור משימה',
  'Create Event' => 'צור אירוע',
  'Update Fields' => 'עדכן שדות',
  'Create Entity' => 'צור רשומה',
  'SMS Task' => 'מטלה',
  'Mobile Push Notification' => 'התראת דחיפה לנייד',
  'LBL_WORKFLOW_NAME' => 'שם זרימת עבודה',
  'LBL_TARGET_MODULE' => 'מודול יעד',
  'LBL_WORKFLOW_TRIGGER' => 'זרימת עבודה',
  'LBL_TRIGGER_WORKFLOW_ON' => 'טריגר זרימת עבודה ב',
  'LBL_RECORD_CREATION' => 'יצירת ברישום',
  'LBL_RECORD_UPDATE' => 'עדכון שיא',
  'LBL_TIME_INTERVAL' => 'מרווח זמן',
  'LBL_RECURRENCE' => 'הישנות',
  'LBL_FIRST_TIME_CONDITION_MET' => 'רק קונדיטונים בפעם הראשונה הם נפגשו',
  'LBL_EVERY_TIME_CONDITION_MET' => 'בכל פעם conditons הם נפגשו',
  'LBL_WORKFLOW_CONDITION' => 'תנאי זרימת עבודה',
  'LBL_WORKFLOW_ACTIONS' => 'פעולות זרימת עבודה',
  'LBL_DELAY_ACTION' => 'עיכוב פעולה',
  'LBL_FREQUENCY' => 'תדירות',
  'LBL_SELECT_FIELDS' => 'בחר שדות',
  'LBL_INCLUDES_CREATION' => 'כולל יצירה',
  'LBL_ACTION_FOR_WORKFLOW' => 'פעולה עבור זרימת עבודה',
  'LBL_WORKFLOW_SEARCH' => 'חפש לפי שם',
  'LBL_ACTION_TYPE' => 'סוג פעולה (ספירה פעילה)',
  'LBL_VTEmailTask' => 'דוא"ל',
  'LBL_VTEntityMethodTask' => 'פונקציה מותאמת אישית',
  'LBL_VTCreateTodoTask' => 'משימה',
  'LBL_VTCreateEventTask' => 'אירוע',
  'LBL_VTUpdateFieldsTask' => 'עדכון שדה',
  'LBL_VTSMSTask' => 'סמס',
  'LBL_VTPushNotificationTask' => 'התראה לנייד',
  'LBL_VTCreateEntityTask' => 'צור רשומה',
  'LBL_MAX_SCHEDULED_WORKFLOWS_EXCEEDED' => 'חרג מהמספר המרבי (% s) של תזרימי עבודה מתוזמנים',
);
$jsLanguageStrings = array (
  'JS_STATUS_CHANGED_SUCCESSFULLY' => 'המצב השתנה בהצלחה',
  'JS_TASK_DELETED_SUCCESSFULLY' => 'הפעולה נמחקה בהצלחה',
  'JS_SAME_FIELDS_SELECTED_MORE_THAN_ONCE' => 'אותם שדות נבחרו יותר מפעם אחת',
  'JS_WORKFLOW_SAVED_SUCCESSFULLY' => 'זרימת העבודה נשמרה בהצלחה',
  'JS_CHECK_START_AND_END_DATE' => 'תאריך הסיום והשעה צריך להיות גדול או שווה ל תאריך ושעה ההתחלה',
  'JS_TASK_STATUS_CHANGED' => 'סטטוס המשימה השתנה בהצלחה.',
  'JS_WORKFLOWS_STATUS_CHANGED' => 'מצב זרימת העבודה השתנה בהצלחה.',
  'VTEmailTask' => 'שלח מייל',
  'VTEntityMethodTask' => 'הפעל פונקציה מותאמת אישית',
  'VTCreateTodoTask' => 'צור משימה',
  'VTCreateEventTask' => 'צור אירוע',
  'VTUpdateFieldsTask' => 'עדכן שדות',
  'VTSMSTask' => 'מטלה',
  'VTPushNotificationTask' => 'התראת דחיפה לנייד',
  'VTCreateEntityTask' => 'צור רשומה',
  'LBL_EXPRESSION_INVALID' => 'הביטוי אינו חוקי',
);
