<?php 

    /*+**********************************************************************************
     * The contents of this file are subject to the vtiger CRM Public License Version 1.0
     * ("License"); You may not use this file except in compliance with the License
     * The Original Code is: vtiger CRM Open Source
     * The Initial Developer of the Original Code is vtiger.
     * Portions created by vtiger are Copyright (C) vtiger.
     * Portions created by Ido Kobelkowsky are Copyright (C) yalla ya!.
     * All Rights Reserved.
     *  ********************************************************************************
     *  Author       : Ido Kobelkowsky
     ************************************************************************************/
    
$languageStrings = array (
  'SINGLE_Documents' => 'מסמך',
  'Documents' => 'מסמכים',
  'LBL_ADD_RECORD' => 'הוסף מסמך',
  'LBL_RECORDS_LIST' => 'רשימת מסמכים',
  'LBL_NOTE_INFORMATION' => 'מידע בסיסי',
  'LBL_FILE_INFORMATION' => 'פרטי קובץ',
  'LBL_DESCRIPTION' => 'תיאור',
  'Title' => 'כותרת',
  'File Name' => 'שם קובץ',
  'Note' => 'הערה',
  'File Type' => 'סוג קובץ',
  'File Size' => 'גודל הקובץ',
  'Download Type' => 'סוג הורדה',
  'Version' => 'גרסה',
  'Active' => 'פעיל',
  'Download Count' => 'ספירת הורדות',
  'Folder Name' => 'שם תיקיה',
  'Document No' => 'מסמך מס',
  'Last Modified By' => 'שונה לאחרונה על ידי',
  'LBL_FOLDER_HAS_DOCUMENTS' => 'העבר מסמכים מתיקייה לפני מחיקתם',
  'LBL_DOWNLOAD_FILE' => 'הורד קובץ',
  'LBL_CHECK_FILE_INTEGRITY' => 'בדוק את שלמות הקובץ',
  'LBL_EMAIL_FILE_AS_ATTACHMENT' => 'שלח קובץ דוא"ל כקובץ מצורף',
  'LBL_INTERNAL' => 'פנימי',
  'LBL_EXTERNAL' => 'חיצוני',
  'LBL_MAX_UPLOAD_SIZE' => 'גודל העלאה מרבי',
  'LBL_MOVE' => 'מהלך \\ לזוז \\ לעבור',
  'LBL_ADD_FOLDER' => 'הוסף תיקיה',
  'LBL_FOLDERS_LIST' => 'רשימת תיקיות',
  'LBL_FOLDERS' => 'תיקיות',
  'LBL_DOCUMENTS_MOVED_SUCCESSFULLY' => 'המסמכים הועברו בהצלחה',
  'LBL_DENIED_DOCUMENTS' => 'מסמכים שנדחו',
  'MB' => 'MB',
  'LBL_ADD_NEW_FOLDER' => 'הוסף תיקייה חדשה',
  'LBL_FOLDER_NAME' => 'שם תיקיה',
  'LBL_FOLDER_DESCRIPTION' => 'תיאור תיקיה',
  'LBL_FILE_AVAILABLE' => 'הקובץ זמין להורדה',
  'LBL_FILE_NOT_AVAILABLE' => 'מסמך זה אינו זמין להורדה',
  'LBL_VIEW_FILE' => 'הצג קובץ',
  'LBL_PREVIEW_NOT_AVAILABLE' => 'תצוגה מקדימה לא זמינה',
  'LBL_INTERNAL_DOCUMENT_TYPE' => 'מסמך פנימי',
  'LBL_EXTERNAL_DOCUMENT_TYPE' => 'כתובת אתר חיצונית',
  'LBL_WEBDOCUMENT_TYPE' => 'מסמך אינטרנט',
  'LBL_DRAG_&_DROP_FILE_HERE' => 'גרור ושחרר קובץ כאן',
  'LBL_WEB' => 'אינטרנט',
  'LBL_UPLOAD_DOCUMENT_TO_VTIGER' => 'העלה מסמכים ל - Vtiger',
  'LBL_UPLOAD_TO_DRIVE' => 'טען אל כונן',
  'LBL_SELECT_FROM_DRIVE' => 'בחר מתוך כונן',
  'LBL_GOOGLE_DRIVE_FOLDERS' => 'תיקיית כונן Google',
  'LBL_ROOT' => 'שורש',
  'LBL_AUTHORIZE' => 'אישור',
  'LBL_DOCUMENT_SOURCE' => 'מקור מסמך',
  'LBL_REVOKE_ACCESS_TO_DRIVE' => 'בטל גישה לכונן',
  'LBL_FILE_URL' => 'כתובת אתר של קובץ',
  'LBL_UPLOAD_TO' => 'להעלות ל',
  'LBL_NEW_DOCUMENT' => 'מסמך חדש',
  'LBL_VTIGER' => 'Vtiger',
  'LBL_CREATE_YOUR_OWN' => 'צור משלך',
  'LBL_SHARE_DOCUMENT' => 'שתף מסמך',
  'LBL_UPLOAD_TO_VTIGER' => 'העלה מסמך ל- Vtiger',
  'LBL_UPLOAD' => 'העלה',
  'LBL_SELECT_FILE_FROM_COMPUTER' => 'בחר קובץ מהמחשב שלי',
  'LBL_FILE_UPLOAD' => 'העלאת קובץ',
  'LBL_LINK_EXTERNAL_DOCUMENT' => 'קישור מסמך חיצוני',
  'LBL_TO_SERVICE' => 'אל% s',
  'LBL_FROM_SERVICE' => 'מ% s',
  'LBL_CREATE_NEW' => 'צור% s חדש',
  'LBL_SELECT_A_FOLDER_TO_MOVE' => 'בחר תיקייה שתעביר אותה',
);
$jsLanguageStrings = array (
  'JS_NEW_FOLDER' => 'תיקייה חדשה',
  'JS_MOVE_DOCUMENTS' => 'העבר מסמכים',
  'JS_ARE_YOU_SURE_YOU_WANT_TO_MOVE_DOCUMENTS_TO' => 'האם אתה בטוח שאתה רוצה להעביר את הקובץ (ים) ל',
  'JS_FOLDER' => 'תיקייה',
  'JS_OPERATION_DENIED' => 'מבצע נדחה',
  'JS_FOLDER_IS_NOT_EMPTY' => 'אנא מחק / העבר את כל המסמכים בתיקייה הנוכחית לפני מחיקתה',
  'JS_SPECIAL_CHARACTERS' => 'תווים מיוחדים כמו',
  'JS_NOT_ALLOWED' => 'לא מורשים',
  'JS_DELETE_AND_TRASH_FILE_IN_DRIVE' => 'מחק קובץ אשפה בכונן',
  'JS_FAILED_TO_UPLOAD_FILE' => 'טעינת הקובץ נכשלה',
  'JS_ARE_YOU_SURE_TO_REVOKE_ACCESS' => 'האם אתה בטוח שברצונך לבטל גישה?',
  'JS_ACCESS_REVOKED' => 'הגישה בוטלה',
  'JS_DELETE_AND_TRASH_FILE_IN_DROPBOX' => 'מחק ואשפה קובץ ב dropbox',
  'JS_UPLOAD_SUCCESSFUL' => 'הקובץ הועלה בהצלחה',
  'JS_UPLOAD_FAILED' => 'טעינת הקובץ נכשלה',
  'JS_DOCUMENT_CREATED' => 'המסמך נוצר',
  'JS_DOCUMENT_CREATION_FAILED' => 'יצירת המסמך נכשלה',
);
